spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.101.1.96:8848
        namespace: 804a877b-82bf-4ac7-8489-7b816b3e4d74
        register-enabled: true

  application:
    name: nacos-server
server:
  port: 7001