spring:
  cloud:
    nacos:
      discovery:
        server-addr: 10.101.0.101:8848
        namespace: 804a877b-82bf-4ac7-8489-7b816b3e4d74
      config:
        server-addr: 10.101.0.101:8848
        file-extension: .yml
        namespace: 804a877b-82bf-4ac7-8489-7b816b3e4d74



  application:
    name: nacos-server
server:
  port: 7001